### ISSUE TITLE
AttributeError: module 'onnx.utils' has no attribute 'polish_model' Trouble

### ISSUE THREAD

**Issue by Ilya-koala** [ORB-HD/deface#19]
Hi, how to fix this problem?
Python 3.8.10
Ubuntu 20.04
Model parameter set to default

**Comment by mdraw** [comment]
This is fixed since https://github.com/ORB-HD/deface/commit/c4b375bbf6fb15171d8de5b75f260277ccbe18c5 but there was no official release since then yet. I've just published version 1.1.1 here and on PyPI, so you can just `pip install --upgrade deface` and the issue should be fixed.

**Comment by Ilya-koala** [comment]
Ok, thanks
