### ISSUE TITLE
problem with mp4

### ISSUE THREAD

**Issue by saebragani** [ORB-HD/deface#2]
This is a great tool, thanks for the good work!
 
However, while I am able to use it to deface videos (mp4) on my local machine (Windows 10), it only works for images but not videos when I try to use it remotely on a Linux-based super-computing cluster. I get the following error when I try it on a video named "cut.mp4":
"**Could not open file cut.mp4 as a video file with imageio. Skipping file...**"
I have tried updating numpy, imageio, scikit-image, tqdm, and imageio-ffmpeg and it still did not work. I appreciate it if you could help me figure this out. Thanks!

**Comment by mdraw** [comment]
Does this error also happen if you just run the following command in the directory of cut.mp4?

    python3 -c "import imageio; next(iter(imageio.get_reader('cut.mp4')))"

If this produces the same error, it's not an issue with deface but there is either something wrong with your imageio installation or with the video itself. I'd try checking the video file for strange properties with `ffprobe` and maybe re-encoding it. Hope this helps!

**Comment by mdraw** [comment]
If this works fine on Windows but not on a Linux-based cluster, I'd also check if there are restrictions to non-free codecs in the Linux distribution (most MP4s use "non-free" codecs AFAIK). You might have to install imageio-ffmpeg differently in that case, see https://github.com/imageio/imageio-ffmpeg#installation.

**Comment by saebragani** [comment]
I upgraded imageio and installed ffmpeg and it worked. Thank you very much!

**Comment by hemc4** [comment]
If anyone facing this issue on mac, it might be due to your temrinal not having disk acess. 
I solved it by providing disk access to terminal app.

https://stackoverflow.com/questions/58479686/permissionerror-errno-1-operation-not-permitted-after-macos-catalina-update
