### ISSUE TITLE
ffmpeg-config issue with fps

### ISSUE THREAD

**Issue by Karl48071** [ORB-HD/deface#24]
Looking at the ffmepg-imageio docs, there does appear to be a parameter called "fps" that changes the output frames per second rate of the anonymized video.  However, when setting ffmpeg-config '{"fps": 15}     I get an error of:  got multiple values for argument 'fps'

How do you properly set that parameter so that the output video is 15 frames per second?

**Comment by mdraw** [comment]
Please update from the latest git version and feel free to reopen if you encounter any problems.

**Comment by Karl48071** [comment]
Thank you!!
