### ISSUE TITLE
Doesn't seem to use hardware acceleration despite it being available

### ISSUE THREAD

**Issue by azsde** [ORB-HD/deface#36]
Hello,

On a fresh install I have very poor performances, looking into it it seems my CPU is doing all the work and my GPU isn't doing anything despite installing the required pip modules.

Is there a log I can provide you to help debug this issue?

**Comment by mdraw** [comment]
Please post the output when running
    $ deface cam --backend=onnxrt

This forces the onnx-runtime backend, which usually tells you in the console output if something is not right.

**Comment by azsde** [comment]
Sorry, my installation was not correct, my GPU is now correctly being used.
