### ISSUE TITLE
Feature Request: Add support for Coral TPU

### ISSUE THREAD

**Issue by Blacknight318** [ORB-HD/deface#38]
I apologize if this has already been looked at, but would there be a way to add the ability to use a Coral TPU(USB) in place of Nvidia Cuda to speed up processing?

**Comment by mdraw** [comment]
Acceleration depends on onnxruntime execution providers. onnxruntime supports [many different EPs](https://onnxruntime.ai/docs/execution-providers/#summary-of-supported-execution-providers) but Coral TPUs are not among them yet. Also see https://github.com/microsoft/onnxruntime/issues/10248.

You could try to convert the ONNX model in `deface` into TFLite format and replace the onnxruntime calls with the corresponding [pycoral code](https://coral.ai/docs/edgetpu/tflite-python/#inferencing-example) in your own fork but that is out of scope of this project.
