### ISSUE TITLE
OpenVino for onnxruntime-openvino

### ISSUE THREAD

**Issue by Blacknight318** [ORB-HD/deface#40]
Please look into adding 'OpenVINOExecutionProvider' to the list of EP's in centerface.py, this offers some Intel acceleration that is better than the standard CPU for Intel chips.

**Comment by mdraw** [comment]
Thanks for the suggestion! Now that there are some prebuilt wheels for onnxruntime-openvino available on PyPI I've tried it out and it actually runs a lot faster than the standard CPU execution on my machine. With the newest commit `OpenVINOExecutionProvider` should be automatically used if available and if no better option such as CUDA is available.

**Comment by StealUrKill** [comment]
> Thanks for the suggestion! Now that there are some prebuilt wheels for onnxruntime-openvino available on PyPI I've tried it out and it actually runs a lot faster than the standard CPU execution on my machine. With the newest commit `OpenVINOExecutionProvider` should be automatically used if available and if no better option such as CUDA is available.

Sorry for replying on a closed issue. I cant seem to get the openvino or directml to work on an intel cpu/integrated gpu at all. I can get the Cuda,Tensor,CPU, and directml to work with nvidia cards. Just wondering what steps i can do to try and fix it.

**Comment by StealUrKill** [comment]
> > Thanks for the suggestion! Now that there are some prebuilt wheels for onnxruntime-openvino available on PyPI I've tried it out and it actually runs a lot faster than the standard CPU execution on my machine. With the newest commit `OpenVINOExecutionProvider` should be automatically used if available and if no better option such as CUDA is available.
> 
> Sorry for replying on a closed issue. I cant seem to get the openvino or directml to work on an intel cpu/integrated gpu at all. I can get the Cuda,Tensor,CPU, and directml to work with nvidia cards. Just wondering what steps i can do to try and fix it.

I ended up getting it corrected but not the normal way. I had to use the openvino archive and not the pypi module as it would never work. Only issue is i have use the setupvars.bat every time. I have created a work around in my windows form app to automatically apply the bat if openvino is selected.
